# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36a555f76996fb3342cb3fc577997cec50fccdc372d00591fb1f773a1025c55ae46c14c964aaa77d8bdadc48ff54a3b8e77f3b11d3b289da0c6b8252017d84ab

test:
  secret_key_base: c2ef3260b11252f7df3221135300e2339f45934e8e8d0c988f5456d7c715bccf34d8c924d46023aa38fb13064ad0c45dc7ac173e3ae5739595baebdc22b00742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
